# Generated by Django 4.0.2 on 2022-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
