# Generated by Django 4.0.2 on 2022-03-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0002_book_age_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=70)),
                ('word_freq', models.FloatField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websearch.book')),
            ],
        ),
    ]
